### ISSUE TITLE
Add a "check" command

### ISSUE THREAD

**Issue by ohad83** [thearegee/bookworms#1]
Hey!

I was thinking of how to make sure my bookmarks repo is updated to the latest yaml changes.
I saw you thought of making use of Github Actions, and while it's a good idea, not everyone uses Github, especially not when this is mostly useful for internal company bookmarks.
I realized having some sort of `check` option, similar to formatters and other tools, which allows you to basically make a "dry run" of the tool and output whether there would be a change if it ran normally. This, just like for formatters, will be very useful for both pre-commit hooks and CI.

If it seems like a reasonable idea, I can go ahead and start implementing it if you don't mind.

**Comment by robinglen** [comment]
hey @ohad83 - you are totally right about github actions - good point.
 
Thank you, I'm really excited to have people contribute and I'm more than happy to have you implement, just so I understand it completely. Would you mind explaining the CI flow you envisage, what it looks like now without the check option and then what the flow looks like with it. This is not because I'm not for the feature but just so I understand it completely 😄

**Comment by ohad83** [comment]
There are 2 flows for this feature I can see:
1. For smaller repos (for example internal repos, which is my use-case), I would use this in a pre-commit hook, mainly to make sure I don't make mistakes. This is for a repo you know and trust the users comitting.
2. For bigger repos (for example the `awesome-whatever` repos), you won't have users comitting into your main repo, but having them fork and open a PR. You can't enforce git hooks on the client side, so what you'd want is a CI test to check whether they ran the tool properly before comitting, to prevent you from mistakenly merging it, and also letting them know there's a problem without you needing to manually check.

P.S this project is a really nice idea, I read the article on medium and immediately realized we have this problem as well, so good job :)

**Comment by robinglen** [comment]
@ohad83 I wasn't sure if it would translate for other people so it's really nice to here, thank you.

Sounds good, please go ahead and I will review the PR when ready

**Comment by robinglen** [comment]
This is now released as 1.3.0
